import { Schema, Table, column } from "@powersync/web";

// Full schema for synced tables. Mirrors integrations/supabase/types.ts.
// PowerSync stores `id` automatically (rowid). All JSON/array columns are
// kept as text and parsed in app code. Booleans are stored as integer 0/1.
export const AppSchema = new Schema({
  products: new Table({
    name: column.text,
    description: column.text,
    barcode: column.text,
    category_id: column.text,
    store_id: column.text,
    supplier_id: column.text,
    unit: column.text,
    image_url: column.text,
    images: column.text, // text[] -> JSON text
    tags: column.text,
    price: column.real,
    original_price: column.real,
    cost_price: column.real,
    local_charges: column.real,
    wholesale_price: column.real,
    vip_price: column.real,
    stock_quantity: column.real,
    is_available: column.integer,
    is_available_online: column.integer,
    is_featured: column.integer,
    nutritional_info: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),
  product_variants: new Table({
    product_id: column.text,
    unit: column.text,
    label: column.text,
    barcode: column.text,
    quantity: column.real,
    price: column.real,
    cost_price: column.real,
    wholesale_price: column.real,
    vip_price: column.real,
    stock_quantity: column.real,
    is_available: column.integer,
    is_default: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  categories: new Table({
    name: column.text,
    slug: column.text,
    description: column.text,
    icon: column.text,
    image_url: column.text,
    parent_id: column.text,
    display_order: column.integer,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  stores: new Table({
    name: column.text,
    address: column.text,
    city: column.text,
    state: column.text,
    zip_code: column.text,
    phone: column.text,
    hours: column.text,
    description: column.text,
    image_url: column.text,
    latitude: column.real,
    longitude: column.real,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  orders: new Table({
    order_number: column.text,
    user_id: column.text,
    customer_id: column.text,
    store_id: column.text,
    address_id: column.text,
    status: column.text,
    payment_method: column.text,
    payment_method_id: column.text,
    payment_status: column.text,
    stripe_payment_intent_id: column.text,
    delivery_date: column.text,
    delivery_time_slot: column.text,
    delivery_instructions: column.text,
    delivered_at: column.text,
    subtotal: column.real,
    tax: column.real,
    delivery_fee: column.real,
    total: column.real,
    created_at: column.text,
    updated_at: column.text,
  }),
  order_items: new Table({
    order_id: column.text,
    product_id: column.text,
    quantity: column.real,
    unit_price: column.real,
    subtotal: column.real,
    created_at: column.text,
  }),
  pos_transactions: new Table({
    transaction_number: column.text,
    store_id: column.text,
    cashier_id: column.text,
    customer_id: column.text,
    payment_method: column.text,
    payment_details: column.text,
    items: column.text,
    metadata: column.text,
    notes: column.text,
    subtotal: column.real,
    tax: column.real,
    discount: column.real,
    total: column.real,
    amount_paid: column.real,
    created_at: column.text,
    updated_at: column.text,
  }),
  cash_sessions: new Table({
    store_id: column.text,
    cashier_id: column.text,
    status: column.text,
    notes: column.text,
    opening_cash: column.real,
    expected_cash: column.real,
    closing_cash: column.real,
    cash_difference: column.real,
    opened_at: column.text,
    closed_at: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),
  purchases: new Table({
    purchase_number: column.text,
    store_id: column.text,
    purchased_by: column.text,
    supplier_name: column.text,
    supplier_contact: column.text,
    payment_method: column.text,
    payment_status: column.text,
    payment_details: column.text,
    notes: column.text,
    total_amount: column.real,
    amount_paid: column.real,
    purchased_at: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),
  purchase_items: new Table({
    purchase_id: column.text,
    product_id: column.text,
    variant_id: column.text,
    quantity: column.real,
    unit_cost: column.real,
    local_charges: column.real,
    total_cost: column.real,
    created_at: column.text,
  }),
  expenses: new Table({
    store_id: column.text,
    account_id: column.text,
    contact_id: column.text,
    paid_from_account_id: column.text,
    created_by: column.text,
    category: column.text,
    description: column.text,
    notes: column.text,
    payment_method: column.text,
    receipt_url: column.text,
    amount: column.real,
    expense_date: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),
  journal_entries: new Table({
    entry_number: column.text,
    description: column.text,
    reference: column.text,
    notes: column.text,
    status: column.text,
    created_by: column.text,
    posted_by: column.text,
    entry_date: column.text,
    posted_at: column.text,
    total_debit: column.real,
    total_credit: column.real,
    transaction_amount: column.real,
    created_at: column.text,
    updated_at: column.text,
  }),
  journal_entry_lines: new Table({
    journal_entry_id: column.text,
    account_id: column.text,
    description: column.text,
    debit_amount: column.real,
    credit_amount: column.real,
    created_at: column.text,
  }),
  accounts: new Table({
    account_code: column.text,
    account_name: column.text,
    account_type: column.text,
    description: column.text,
    parent_account_id: column.text,
    created_by: column.text,
    opening_balance: column.real,
    current_balance: column.real,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  contacts: new Table({
    name: column.text,
    contact_person: column.text,
    email: column.text,
    phone: column.text,
    address_line1: column.text,
    address_line2: column.text,
    city: column.text,
    state: column.text,
    country: column.text,
    zip_code: column.text,
    tax_id: column.text,
    notes: column.text,
    price_tier: column.text,
    custom_price_tier_id: column.text,
    customer_ledger_account_id: column.text,
    supplier_ledger_account_id: column.text,
    created_by: column.text,
    credit_limit: column.real,
    discount_percentage: column.real,
    opening_balance: column.real,
    supplier_opening_balance: column.real,
    is_customer: column.integer,
    is_supplier: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  pos_users: new Table({
    full_name: column.text,
    pin_hash: column.text,
    user_id: column.text,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  addresses: new Table({
    user_id: column.text,
    label: column.text,
    address_line1: column.text,
    address_line2: column.text,
    city: column.text,
    state: column.text,
    zip_code: column.text,
    phone: column.text,
    latitude: column.real,
    longitude: column.real,
    is_default: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  announcements: new Table({
    title: column.text,
    message: column.text,
    background_color: column.text,
    background_image_url: column.text,
    text_color: column.text,
    title_font_size: column.text,
    title_font_weight: column.text,
    message_font_size: column.text,
    message_font_weight: column.text,
    start_date: column.text,
    end_date: column.text,
    display_order: column.integer,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
});

export type Database = (typeof AppSchema)["types"];

export type Database = (typeof AppSchema)["types"];