import { Schema, Table, column } from "@powersync/web";

// Full schema for synced tables. Mirrors integrations/supabase/types.ts.
// PowerSync stores `id` automatically (rowid). All JSON/array columns are
// kept as text and parsed in app code. Booleans are stored as integer 0/1.
export const AppSchema = new Schema({
  products: new Table({
    name: column.text,
    description: column.text,
    barcode: column.text,
    category_id: column.text,
    store_id: column.text,
    supplier_id: column.text,
    unit: column.text,
    image_url: column.text,
    images: column.text, // text[] -> JSON text
    tags: column.text,
    price: column.real,
    original_price: column.real,
    cost_price: column.real,
    local_charges: column.real,
    wholesale_price: column.real,
    vip_price: column.real,
    stock_quantity: column.real,
    is_available: column.integer,
    is_available_online: column.integer,
    is_featured: column.integer,
    nutritional_info: column.text,
    created_at: column.text,
    updated_at: column.text,
  }, { indexes: { name_idx: ['name'], barcode_idx: ['barcode'], store_idx: ['store_id'], category_idx: ['category_id'] } }),
  product_variants: new Table({
    product_id: column.text,
    unit: column.text,
    label: column.text,
    barcode: column.text,
    quantity: column.real,
    price: column.real,
    cost_price: column.real,
    wholesale_price: column.real,
    vip_price: column.real,
    stock_quantity: column.real,
    is_available: column.integer,
    is_default: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }, { indexes: { product_idx: ['product_id'], barcode_idx: ['barcode'] } }),
  categories: new Table({
    name: column.text,
    slug: column.text,
    description: column.text,
    icon: column.text,
    image_url: column.text,
    parent_id: column.text,
    display_order: column.integer,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  stores: new Table({
    name: column.text,
    address: column.text,
    city: column.text,
    state: column.text,
    zip_code: column.text,
    phone: column.text,
    hours: column.text,
    description: column.text,
    image_url: column.text,
    latitude: column.real,
    longitude: column.real,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  orders: new Table({
    order_number: column.text,
    user_id: column.text,
    customer_id: column.text,
    store_id: column.text,
    address_id: column.text,
    status: column.text,
    payment_method: column.text,
    payment_method_id: column.text,
    payment_status: column.text,
    stripe_payment_intent_id: column.text,
    delivery_date: column.text,
    delivery_time_slot: column.text,
    delivery_instructions: column.text,
    delivered_at: column.text,
    subtotal: column.real,
    tax: column.real,
    delivery_fee: column.real,
    total: column.real,
    created_at: column.text,
    updated_at: column.text,
  }),
  order_items: new Table({
    order_id: column.text,
    product_id: column.text,
    quantity: column.real,
    unit_price: column.real,
    subtotal: column.real,
    created_at: column.text,
  }),
  pos_transactions: new Table({
    transaction_number: column.text,
    store_id: column.text,
    cashier_id: column.text,
    customer_id: column.text,
    payment_method: column.text,
    payment_details: column.text,
    items: column.text,
    metadata: column.text,
    notes: column.text,
    subtotal: column.real,
    tax: column.real,
    discount: column.real,
    total: column.real,
    amount_paid: column.real,
    created_at: column.text,
    updated_at: column.text,
  }),
  cash_sessions: new Table({
    store_id: column.text,
    cashier_id: column.text,
    status: column.text,
    notes: column.text,
    opening_cash: column.real,
    expected_cash: column.real,
    closing_cash: column.real,
    cash_difference: column.real,
    opened_at: column.text,
    closed_at: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),
  purchases: new Table({
    purchase_number: column.text,
    store_id: column.text,
    purchased_by: column.text,
    supplier_name: column.text,
    supplier_contact: column.text,
    payment_method: column.text,
    payment_status: column.text,
    payment_details: column.text,
    notes: column.text,
    total_amount: column.real,
    amount_paid: column.real,
    purchased_at: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),
  purchase_items: new Table({
    purchase_id: column.text,
    product_id: column.text,
    variant_id: column.text,
    quantity: column.real,
    unit_cost: column.real,
    local_charges: column.real,
    total_cost: column.real,
    created_at: column.text,
  }),
  expenses: new Table({
    store_id: column.text,
    account_id: column.text,
    contact_id: column.text,
    paid_from_account_id: column.text,
    created_by: column.text,
    category: column.text,
    description: column.text,
    notes: column.text,
    payment_method: column.text,
    receipt_url: column.text,
    amount: column.real,
    expense_date: column.text,
    created_at: column.text,
    updated_at: column.text,
  }),
  journal_entries: new Table({
    entry_number: column.text,
    description: column.text,
    reference: column.text,
    notes: column.text,
    status: column.text,
    created_by: column.text,
    posted_by: column.text,
    entry_date: column.text,
    posted_at: column.text,
    total_debit: column.real,
    total_credit: column.real,
    transaction_amount: column.real,
    created_at: column.text,
    updated_at: column.text,
  }),
  journal_entry_lines: new Table({
    journal_entry_id: column.text,
    account_id: column.text,
    description: column.text,
    debit_amount: column.real,
    credit_amount: column.real,
    created_at: column.text,
  }),
  accounts: new Table({
    account_code: column.text,
    account_name: column.text,
    account_type: column.text,
    description: column.text,
    parent_account_id: column.text,
    created_by: column.text,
    opening_balance: column.real,
    current_balance: column.real,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  contacts: new Table({
    name: column.text,
    contact_person: column.text,
    email: column.text,
    phone: column.text,
    address_line1: column.text,
    address_line2: column.text,
    city: column.text,
    state: column.text,
    country: column.text,
    zip_code: column.text,
    tax_id: column.text,
    notes: column.text,
    price_tier: column.text,
    custom_price_tier_id: column.text,
    customer_ledger_account_id: column.text,
    supplier_ledger_account_id: column.text,
    created_by: column.text,
    credit_limit: column.real,
    discount_percentage: column.real,
    opening_balance: column.real,
    supplier_opening_balance: column.real,
    is_customer: column.integer,
    is_supplier: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }, { indexes: { supplier_idx: ['is_supplier'], customer_idx: ['is_customer'], name_idx: ['name'] } }),
  pos_users: new Table({
    full_name: column.text,
    pin_hash: column.text,
    user_id: column.text,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  addresses: new Table({
    user_id: column.text,
    label: column.text,
    address_line1: column.text,
    address_line2: column.text,
    city: column.text,
    state: column.text,
    zip_code: column.text,
    phone: column.text,
    latitude: column.real,
    longitude: column.real,
    is_default: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  announcements: new Table({
    title: column.text,
    message: column.text,
    background_color: column.text,
    background_image_url: column.text,
    text_color: column.text,
    title_font_size: column.text,
    title_font_weight: column.text,
    message_font_size: column.text,
    message_font_weight: column.text,
    start_date: column.text,
    end_date: column.text,
    display_order: column.integer,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  purchase_orders: new Table({
    po_number: column.text,
    store_id: column.text,
    supplier_id: column.text,
    supplier_name: column.text,
    supplier_email: column.text,
    supplier_phone: column.text,
    status: column.text,
    notes: column.text,
    share_token: column.text,
    created_by: column.text,
    valid_until: column.text,
    created_at: column.text,
    updated_at: column.text,
  }, { indexes: { store_idx: ['store_id'], supplier_idx: ['supplier_id'] } }),
  purchase_order_items: new Table({
    purchase_order_id: column.text,
    product_id: column.text,
    variant_id: column.text,
    product_name: column.text,
    variant_name: column.text,
    requested_quantity: column.real,
    created_at: column.text,
  }, { indexes: { po_idx: ['purchase_order_id'] } }),
  payment_receipts: new Table({
    receipt_number: column.text,
    store_id: column.text,
    contact_id: column.text,
    received_by: column.text,
    payment_method: column.text,
    reference: column.text,
    notes: column.text,
    amount: column.real,
    payment_date: column.text,
    created_at: column.text,
    updated_at: column.text,
  }, { indexes: { contact_idx: ['contact_id'], store_idx: ['store_id'] } }),
  supplier_payments: new Table({
    payment_number: column.text,
    store_id: column.text,
    contact_id: column.text,
    purchase_id: column.text,
    paid_by: column.text,
    payment_method: column.text,
    reference: column.text,
    notes: column.text,
    amount: column.real,
    payment_date: column.text,
    created_at: column.text,
    updated_at: column.text,
  }, { indexes: { contact_idx: ['contact_id'], store_idx: ['store_id'] } }),
  payment_methods: new Table({
    user_id: column.text,
    label: column.text,
    type: column.text,
    last_four: column.text,
    stripe_payment_method_id: column.text,
    expiry_month: column.integer,
    expiry_year: column.integer,
    is_default: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  stock_adjustments: new Table({
    product_id: column.text,
    variant_id: column.text,
    store_id: column.text,
    adjustment_type: column.text,
    reason: column.text,
    adjusted_by: column.text,
    inventory_layer_id: column.text,
    cost_source: column.text,
    journal_entry_id: column.text,
    quantity_change: column.real,
    unit_cost: column.real,
    total_value: column.real,
    cogs_amount: column.real,
    created_at: column.text,
  }, { indexes: { product_idx: ['product_id'], variant_idx: ['variant_id'], store_idx: ['store_id'] } }),
  productions: new Table({
    production_number: column.text,
    status: column.text,
    notes: column.text,
    source_product_id: column.text,
    source_variant_id: column.text,
    created_by: column.text,
    source_quantity: column.real,
    production_date: column.text,
    created_at: column.text,
    updated_at: column.text,
  }, { indexes: { source_product_idx: ['source_product_id'], source_variant_idx: ['source_variant_id'] } }),
  production_outputs: new Table({
    production_id: column.text,
    product_id: column.text,
    variant_id: column.text,
    quantity: column.real,
    created_at: column.text,
  }, { indexes: { production_idx: ['production_id'] } }),
  offers: new Table({
    title: column.text,
    description: column.text,
    image_url: column.text,
    link_url: column.text,
    start_date: column.text,
    end_date: column.text,
    discount_percentage: column.real,
    display_order: column.integer,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  bogo_offers: new Table({
    name: column.text,
    description: column.text,
    buy_product_id: column.text,
    buy_variant_id: column.text,
    get_product_id: column.text,
    get_variant_id: column.text,
    buy_quantity: column.integer,
    get_quantity: column.integer,
    get_discount_percentage: column.integer,
    start_date: column.text,
    end_date: column.text,
    max_total_uses: column.integer,
    max_uses_per_transaction: column.integer,
    current_uses: column.integer,
    display_order: column.integer,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  special_offers: new Table({
    name: column.text,
    match_mode: column.text,
    store_id: column.text,
    discount_percentage: column.real,
    threshold_amount: column.real,
    is_active: column.integer,
    created_at: column.text,
    updated_at: column.text,
  }),
  quotations: new Table({
    quotation_number: column.text,
    customer_name: column.text,
    customer_email: column.text,
    customer_phone: column.text,
    contact_id: column.text,
    status: column.text,
    notes: column.text,
    items: column.text, // jsonb -> text
    created_by: column.text,
    subtotal: column.real,
    discount: column.real,
    tax: column.real,
    total: column.real,
    valid_until: column.text,
    created_at: column.text,
    updated_at: column.text,
  }, { indexes: { contact_idx: ['contact_id'], status_idx: ['status'] } }),
});

export type Database = (typeof AppSchema)["types"];