-- Insert new categories based on the website
INSERT INTO categories (name, slug, icon, description, display_order, is_active) VALUES
('Agarbatti', 'agarbatti', '🕉️', 'Incense sticks and spiritual items', 1, true),
('Baby', 'baby', '👶', 'Baby care products and essentials', 2, true),
('Beer', 'beer', '🍺', 'Beer and alcoholic beverages', 3, true),
('Biscuits', 'biscuits', '🍪', 'Biscuits and cookies', 4, true),
('Butter - Mayo - Jam', 'butter-mayo-jam', '🧈', 'Spreads, butter, mayonnaise, and jams', 5, true),
('Candies', 'candies', '🍬', 'Candies and confectionery', 6, true),
('Chips', 'chips', '🥔', 'Chips and savory snacks', 7, true),
('Chocolates', 'chocolates', '🍫', 'Chocolates and sweet treats', 8, true),
('Conserves', 'conserves', '🥫', 'Canned and preserved foods', 9, true),
('Cosmetics', 'cosmetics', '💄', 'Beauty and cosmetic products', 10, true),
('Dental Care', 'dental-care', '🦷', 'Dental hygiene products', 11, true),
('Desserts', 'desserts', '🍰', 'Desserts and sweet items', 12, true),
('Detergents', 'detergents', '🧼', 'Laundry and cleaning detergents', 13, true),
('Dry Fruits', 'dry-fruits', '🌰', 'Dried fruits and nuts', 14, true),
('Flour', 'flour', '🌾', 'Flour and baking ingredients', 15, true),
('Furnitures', 'furnitures', '🪑', 'Household furniture items', 16, true),
('Global Market', 'global-market', '🌍', 'International products', 17, true),
('Grains', 'grains', '🌾', 'Grains and cereals', 18, true),
('Grocery', 'grocery', '🛒', 'General grocery items', 19, true),
('Hygienes', 'hygienes', '🧴', 'Personal hygiene products', 20, true),
('Catchup - Moutardes', 'ketchup-mustards', '🍅', 'Ketchup, mustards, and condiments', 21, true),
('Milk - Yogurt - Cheese', 'milk-yogurt-cheese', '🥛', 'Dairy products', 22, true),
('Oils', 'oils', '🫒', 'Cooking oils and fats', 23, true),
('Perfumes - Deos', 'perfumes-deos', '🌸', 'Perfumes and deodorants', 24, true),
('Pasta and Noodles', 'pasta-noodles', '🍝', 'Pasta, noodles, and related products', 25, true),
('Pickles', 'pickles', '🥒', 'Pickles and preserved vegetables', 26, true),
('Products', 'products', '📦', 'General products', 27, true),
('Produit - Capliaries', 'produit-capliaries', '💇', 'Hair care products', 28, true),
('Rice - Couscous', 'rice-couscous', '🍚', 'Rice, couscous, and grain products', 29, true),
('Salt', 'salt', '🧂', 'Salt and seasonings', 30, true),
('Souces', 'sauces', '🥫', 'Sauces and gravies', 31, true),
('Soaps', 'soaps', '🧼', 'Soaps and body wash', 32, true),
('Soda/Juice', 'soda-juice', '🥤', 'Soft drinks and juices', 33, true),
('Spices', 'spices', '🌶️', 'Spices and seasonings', 34, true),
('Sports', 'sports', '⚽', 'Sports and fitness items', 35, true),
('Sugar', 'sugar', '🍬', 'Sugar and sweeteners', 36, true),
('Sweets', 'sweets', '🍭', 'Sweet items and confections', 37, true),
('Tea - Coffee', 'tea-coffee', '☕', 'Tea, coffee, and hot beverages', 38, true),
('Tobacco', 'tobacco', '🚬', 'Tobacco products', 39, true),
('Vinegars', 'vinegars', '🍶', 'Vinegars and cooking acids', 40, true),
('Water', 'water', '💧', 'Bottled water and beverages', 41, true),
('Whisky - Liquers', 'whisky-liquers', '🥃', 'Whisky, liqueurs, and spirits', 42, true),
('Wines', 'wines', '🍷', 'Wines and wine products', 43, true);