// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const CLOUD_SUPABASE_URL = "https://wvdrsofehwiopbkzrqit.supabase.co";
const CLOUD_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2ZHJzb2ZlaHdpb3Bia3pycWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NzE1NjUsImV4cCI6MjA3NjA0NzU2NX0.GH5r-1xInHsL_EyzMOTVtb2QWIImuyJe-_ysqF0LCQ0";

// Check for local Supabase configuration (set via Settings page or localStorage)
export const getSupabaseConfig = () => {
  try {
    const localConfig = localStorage.getItem('local_supabase_config');
    if (localConfig) {
      const config = JSON.parse(localConfig);
      if (config.url && config.anonKey) {
        return { url: config.url, key: config.anonKey, isLocal: true };
      }
    }
  } catch (error) {
    console.error('Error reading local Supabase config:', error);
  }
  return { url: CLOUD_SUPABASE_URL, key: CLOUD_SUPABASE_KEY, isLocal: false };
};

// Create supabase client - reads config at initialization
const createSupabaseClient = (): SupabaseClient<Database> => {
  const config = getSupabaseConfig();
  console.log('[Supabase] Creating client with URL:', config.url, 'isLocal:', config.isLocal);
  
  return createClient<Database>(config.url, config.key, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
};

// The supabase client instance
export const supabase = createSupabaseClient();

// Log current config on load
const currentConfig = getSupabaseConfig();
console.log('[Supabase] Active config - URL:', currentConfig.url, 'isLocal:', currentConfig.isLocal);

// Helper to update local Supabase config (call this from Settings)
export const setLocalSupabaseConfig = (url: string, anonKey: string) => {
  console.log('[Supabase] Setting local config:', url);
  localStorage.setItem('local_supabase_config', JSON.stringify({ url, anonKey }));
  // Reload to apply new config
  window.location.reload();
};

export const clearLocalSupabaseConfig = () => {
  console.log('[Supabase] Clearing local config');
  localStorage.removeItem('local_supabase_config');
  window.location.reload();
};

export const getLocalSupabaseConfigStatus = () => {
  try {
    const localConfig = localStorage.getItem('local_supabase_config');
    if (localConfig) {
      return JSON.parse(localConfig);
    }
  } catch (error) {
    console.error('Error reading local config:', error);
  }
  return null;
};

// Check if currently using local Supabase
export const isUsingLocalSupabase = (): boolean => {
  return getSupabaseConfig().isLocal;
};
